[package]
name = "vehicle-manager-actix-web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
paperclip = { version = "0.9", features = ["actix4"] }
mongodb = "3"
log = "0.4"